---
all:
  children:
    boxes:
      children:
        cloud:
          hosts:
            something:
              ansible_host: 164.92.79.36
              ansible_user: root
              ansible_python_interpreter: /usr/bin/python3
