---
all:
  children:
    boxes:
      children:
        cloud:
          hosts:
            dockerhost.cg.home.arpa:
            nvidia.cg.home.arpa:
              # ansible_host: 164.92.79.36
              # ansible_user: root
