---
all:
  children:
    boxes:
      children:
        cloud:
          hosts:
            something:
              ansible_host: 5.78.89.198
              ansible_user: shiv
              ansible_python_interpreter: /usr/bin/python3
