---
- hosts: cloud
  gather_facts: yes
  become: yes

  tasks:
    - name: nginx
      apt:
        name: nginx
        state: present

    # apt autoremove -y --purge

    - name: Remove unnecessary dependencies
      apt:
        autoremove: yes

    - name: is file to fit karo
      ansible.builtin.copy:
        src: index.html
        # dest: /usr/share/nginx/html
        dest: /var/www/html/index.nginx-debian.html
